env:
  browser: true
  es2021: true
  jest: true
extends:
  - eslint:recommended
  - plugin:vue/vue3-essential
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - prettier
  - vue
rules: {
  prettier/prettier: error
}
