development: &default
  locker_floors: &locker_floors
    ? A floor
    ? B floor
    ? C floor
    ? 2nd floor
    ? 3rd floor
  locker_floor_choices:
    ? No preference
    << : *locker_floors
  study_room_locations:
    - Classics Graduate Study Room
    - German Graduate Study Room
    - History Graduate Study Room
    - Religion Graduate Study Room
  locker_sizes:
    - 4
    - 6
  semesters:
    - Fall
    - Spring
  statuses:
    - senior
    - junior
    - graduate
    - faculty
    - staff

test:
  <<: *default

production:
  <<: *default

staging:
  <<: *default
