development: &default
  accessibility_needs_choices:
    keyed_entry: Keyed entry (rather than combination)
    near_elevator: Near an elevator
  firestone_locker_floors: &firestone_locker_floors
    ? A floor
    ? B floor
    ? C floor
    ? 2nd floor
    ? 3rd floor
  lewis_locker_floors: &lewis_locker_floors
    ? 3rd floor
    ? 4th floor
  firestone_locker_floor_choices:
    ? No preference
    << : *firestone_locker_floors
  lewis_locker_floor_choices:
    ? No preference
    << : *lewis_locker_floors
  study_room_locations:
    - Classics Graduate Study Room
    - History Graduate Study Room
    # these existed in the old system, but do not have any locations assigned to them in the recent past
    # - German Graduate Study Room
    # - Religion Graduate Study Room
  locker_sizes:
    "Firestone Library": &firestone_locker_sizes
      - 4
      - 6
    "Lewis Library": &lewis_locker_sizes
      - 2
  semesters:
    - Fall
    - Spring
  statuses:
    - senior
    - junior
    - graduate
    - faculty
    - staff

test:
  <<: *default

production:
  <<: *default

staging:
  <<: *default
